const mockContacts = [
  {
    id: "1",
    image: "image_url_1.jpg",
    firstName: "Lily",
    lastName: "Adams",
    bio: "Chasing sunsets and vibes at every festival!",
    email: "lily.adams@example.com",
    instagram: "@lilyadams",
    snapchat: "@lilySnap",
    facebook: "facebook.com/lilyadams",
    phonenumber: "123-456-7890",
  },
  {
    id: "2",
    image: "image_url_2.jpg",
    firstName: "Ethan",
    lastName: "Miller",
    bio: "Dancing like nobody's watching since 2015.",
    email: "ethan.miller@example.com",
    instagram: "@ethanmiller",
    snapchat: "@ethanSnap",
    facebook: "facebook.com/ethanmiller",
    phonenumber: "234-567-8901",
  },
  {
    id: "3",
    image: "image_url_3.jpg",
    firstName: "Chloe",
    lastName: "Johnson",
    bio: "Living for the beats and the friends I make along the way.",
    email: "chloe.johnson@example.com",
    instagram: "@chloejohnson",
    snapchat: "@chloeSnap",
    facebook: "facebook.com/chloejohnson",
    phonenumber: "345-678-9012",
  },
  {
    id: "4",
    image: "image_url_4.jpg",
    firstName: "Zoe",
    lastName: "Williams",
    bio: "Collecting memories and wristbands one festival at a time.",
    email: "zoe.williams@example.com",
    instagram: "@zoewilliams",
    snapchat: "@zoeSnap",
    facebook: "facebook.com/zoewilliams",
    phonenumber: "456-789-0123",
  },
  {
    id: "5",
    image: "image_url_5.jpg",
    firstName: "Ryan",
    lastName: "Garcia",
    bio: "Found my tribe under the stars and neon lights.",
    email: "ryan.garcia@example.com",
    instagram: "@ryangarcia",
    snapchat: "@ryanSnap",
    facebook: "facebook.com/ryangarcia",
    phonenumber: "567-890-1234",
  },
  {
    id: "6",
    image: "image_url_6.jpg",
    firstName: "Mia",
    lastName: "Martinez",
    bio: "Karaoke queen and glitter enthusiast—let's sing it loud!",
    email: "mia.martinez@example.com",
    instagram: "@miamartinez",
    snapchat: "@miaSnap",
    facebook: "facebook.com/miamartinez",
    phonenumber: "678-901-2345",
  },
];

export default mockContacts;
